---
# This playbook deploys a pihole server.

- name: Apply common config
  hosts: pihole
  remote_user: jack
  become: yes
  
  roles:
    - common

- name: Install pihole
  hosts: pihole
  remote_user: jack
  become: yes

  roles:
    - pihole
